waypoints:
  A:
    x: 0.0
    y: 0.0
    yaw: 0.0
  B:
    x: 0.0
    y: 0.0
    yaw: 0.0
  C:
    x: 0.0
    y: 0.0
    yaw: 0.0
  原点:
    x: 0.0
    y: 0.0
    yaw: 0.0
  夹取点:
    x: 0.4739
    y: -1.2099
    yaw: -1.4807
  投放点:
    x: 2.488
    y: 0.2894
    yaw: -0.1905
  水果区:
    x: 2.3932
    y: 0.8178
    yaw: 0.2183
  足球区:
    x: 0.4321
    y: -0.7673
    yaw: -1.4263
  饮品区:
    x: 2.3658
    y: -0.8135
    yaw: -0.505
